name: meister2
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  get: ^4.6.5
  flutter_svg: ^2.0.5
  infinite_scroll_pagination: ^3.2.0
  firebase_messaging: ^14.5.0
  firebase_auth: ^4.5.0
  google_sign_in: ^6.1.0
  shared_preferences: ^2.0.15
  carousel_slider: ^4.2.1
  package_info_plus: ^4.0.2
  photo_view: ^0.14.0
  permission_handler: ^10.0.1
  file_picker: ^5.2.0+1
  device_info_plus: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/